name: Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.4
      - name: Build and Test
        run: |
          yarn
          # yarn build
          # yarn test
